[package]
name = "actix_example"
version = "0.1.0"
edition = "2021"

[dependencies]
actix-web = "4"
tera = "1"
lazy_static = "1.5.0"
actix-files = "0.6.6"
rand = "0.8.5"
serde = { version = "1.0.218", features = ["derive"] }
serde_json = "1"
futures = "0.3"
