# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema/schema.rs"
custom_type_derives = ["diesel::sql_types::QueryId","diesel::sql_types::SqlType", "std::fmt::Debug"]
generate_missing_sql_type_definitions = true

[migrations_directory]
dir = "migrations"
